### ISSUE TITLE
Build of `ffmpeg-sys` works, but using it as a dependency fails

### ISSUE THREAD

**Issue by gcohara** [meh/rust-ffmpeg-sys#102]
With the following code

```
use ffmpeg_sys::*;

fn main() {
    let hi: ffmpeg_sys::__va_list_tag;
    println!("Hello, world!");
}
```
and the following `Cargo.toml`
```
[package]
name = "ffmpeg_sys_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-sys="4.3.3"
```
`cargo build` fails with the following error
```
error[E0412]: cannot find type `__va_list_tag` in crate `ffmpeg_sys`
 --> src/main.rs:4:25
  |
4 |     let hi: ffmpeg_sys::__va_list_tag;
  |                         ^^^^^^^^^^^^^ not found in `ffmpeg_sys`
```

There is no problem with building `ffmpeg-sys` by itself.

This is on Apple silicon, macOS 12.3.1 with ffmpeg 4.4.2 installed via `brew install -s ffmpeg@4` and all the relevant paths added to `.bash_profile`. I also tried passing the `build` feature flag to `ffmpeg-sys`.

**Comment by kornelski** [comment]
You're not supposed to be using `__va_list_tag`. It's an internal name for a C macro that is not usable in Rust. It might have gotten exported by bindgen, but that's a bindgen or libclang bug.

**Comment by gcohara** [comment]
Sure, thanks for getting back to me @kornelski !

My further investigations revealed that this was architecture dependent - I think it's related to a usage of `sprintf` within our codebase. arm64 doesn't have `__va_list_tag` in its stdlib I guess.

Agree that this is best to raise with `bindgen` as it's appearing in the docs for a few crates that use it.
