### ISSUE TITLE
Incorrect struct fields in AVFormatContext

### ISSUE THREAD

**Issue by Luminarys** [meh/rust-ffmpeg-sys#31]
In the update from ffmpeg 2.8 to 3.0, the AVFormatContext has changed very slightly. This change is subtle enough to allow for the FFI version of this struct to not fail completely, but enough to screw up the alignment of about half of the fields and invalidate them(I found this out trying to use the rust-ffmpeg examples and having them segfault).

In order to update to 3.0 properly, the open_cb field should be removed and replaced with io_open, and io_close, the bit_rate field should be changed to an in64_t, and a protocol_whitelist field should be added in. To update to 3.1 in addition to the previous changes, a protocol_blacklist field should be added. For reference, here is the [ffmpeg documentation](https://www.ffmpeg.org/doxygen/3.0/structAVFormatContext.html).

**Comment by panicbit** [comment]
To avoid this issue in the future I think one could expose the fields exclusively via extern methods and some C glue at the cost of some function call overhead.

**Comment by Luminarys** [comment]
In the end there's not much you can do, except maybe use something like bindgen to automatically create the corresponding Rust files. At any rate now that 7257cb1 is merged, I'm closing the issue.
