### ISSUE TITLE
Build failures due to missing libavresample

### ISSUE THREAD

**Issue by hatzel** [meh/rust-ffmpeg-sys#65]
The package won't build on recent Archlinux installations [due to libavresample being dropped.](https://www.archlinux.org/todo/libavresample-drop/).

This is expected behavior in the normal configuration, the lib is, after all, missing. When however disabling the respective feature the build will still fail with: "Package libavresample was not found in the pkg-config search path"

This is due to pkg-conf being called regardless of the feature being enabled. I wrote a quick fix for this in `build.rs`. Not sure if this is a great solution so let me know if you need any changes. The PR will follow in a minute.

This bug doesn't occur when `FFMPEG_DIR` is set.

**Comment by barzamin** [comment]
closed by #63

**Comment by hatzel** [comment]
This is not actually fixed by #63. As laid out in the initial issue under certain conditions the build process looks for the library (using pkg-conf) even if the feature is disabled.
