### ISSUE TITLE
Publish version 4.0.2 to crate ?

### ISSUE THREAD

**Issue by LuoZijun** [meh/rust-ffmpeg-sys#68]
Publish current version 4.0.2 to crate ?

**Comment by barzamin** [comment]
I think only @meh has the permissions required to do that.

**Comment by chvp** [comment]
Echoing the call for a publish, preferably with the latest PR (#66) included.

**Comment by LuoZijun** [comment]
@charvp This Line https://github.com/meh/rust-ffmpeg-sys/blob/master/Cargo.toml#L3 has already bumped version.

**Comment by MarcAntoine-Arnaud** [comment]
Hi,

We have currently forked and rename the project to update the repository (updated with FFMpeg 4.2.1):
https://github.com/media-io/stainless-ffmpeg-sys

We have done that to publish in open-source this project to easiest create ffmpeg job:
https://github.com/nomalab/stainless-ffmpeg
Any comment is welcome !

Marc-Antoine

**Comment by kornelski** [comment]
ping
